[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
